# Generated by Django 4.1 on 2023-09-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'Done ✔️'), ('P', 'Pending ⏳')], max_length=2),
        ),
    ]
